project:
  type: website
  output-dir: docs

website:
  title: "Rafi @ Reyes"
  navbar:
    logo: images/tanque.jpg
    left:
      - href: index.qmd
        text: Inicio
      - href: mapas_guia.qmd
        text: Mapas
      - href: proyectos.qmd
        text: Proyectos
      - href: contacto.qmd
        text: Contacto
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/jnut/
      - icon: github
        href: https://github.com/jurteagat
      - icon: youtube
        href: https://www.youtube.com/@jurteagat/


format:
  html:
    theme:
      light: minty
      dark: darkly
    respect-user-color-scheme: true
    toc: true
    toc-location: left
    toc-depth: 2


editor: visual
